datapull:
  application:
    region: us-west-2
  secretstore:
    vault:
      vault_url:
      static_secret_path_prefix:
      vault_nonce:
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-filesystem.json
  spark:
    network: spark.network.timeout
    timeout: 10000s
    executor: spark.executor.heartbeatInterval
    interval: 1000s
    broadcasttimeout: spark.sql.broadcastTimeout
    btimeout: 36000
    scheduler: spark.scheduler.mode
    mode: FAIR
    failures: spark.task.maxFailures
  miscellaneous:
    no_of_retries: 16
    timeout: 10000
    consul_url:
    sleeptimeout: 60000
  api:
    s3_bucket_name: 771905877782-datatools-datapull
    application_subnet_1: subnet-00bcae6ec0bb9bef1
    application_subnet_2: subnet-0e72891c187bdd828
    application_security_group: sg-04670349cebceffbe
    vpc_id: vpc-04507fdcde9c2020c
    load_balancer_certificate_arn: arn:aws:acm:us-west-2:771905877782:certificate/2b1d3629-aa6d-47d5-8902-d0f9e75b35a7
  emr:
    emr_security_group_master:
    emr_security_group_slave:
    emr_security_group_service_access:
    tags:
      Brand:
      Category: EMRPipeline
      Owner:
      Purpose: EMRPipeline
      Service: emr
      Platform: EMRPipeline
  logger:
    cloudwatch:
      groupName: /ecs/datatools-datapull-api
      streamName: datapull-stream
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  email:
    smtp:
      emailaddress:
      smtpserveraddress:
    ses:
      region:
      email:
      access_key:
      secret_key:
