datapull:
  application:
    region: us-west-2
  secretstore:
    vault:
      vault_url:
      static_secret_path_prefix:
      vault_nonce:
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-filesystem.json
  spark:
    network: spark.network.timeout
    timeout: 10000s
    executor: spark.executor.heartbeatInterval
    interval: 1000s
    broadcasttimeout: spark.sql.broadcastTimeout
    btimeout: 36000
    scheduler: spark.scheduler.mode
    mode: FAIR
    failures: spark.task.maxFailures
  miscellaneous:
    no_of_retries: 16
    timeout: 10000
    consul_url:
    sleeptimeout: 60000
  api:
    s3_bucket_name: epc-datapull-lodgingpartnerp-prodp
    application_subnet_1: subnet-4eaee037
    application_subnet_2: subnet-af89d1f5
    application_security_group: sg-059171947c2f6f8cd
    vpc_id: vpc-bc9a68c4
    load_balancer_certificate_arn:
  emr:
    emr_security_group_master:
    emr_security_group_slave:
    emr_security_group_service_access:
    tags:
      Brand:
      Category: EMRPipeline
      Owner:
      Purpose: EMRPipeline
      Service: emr
      Platform: EMRPipeline
  logger:
    cloudwatch:
      groupName: /ecs/datapull-web-api
      streamName: datapull-stream
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  email:
    smtp:
      emailaddress:
      smtpserveraddress:
    ses:
      region: us-west-2
      email: obeng@expedia.com
      access_key:
      secret_key:
